import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar/Navbar";
import Provider from "@/components/Provider/Provider";
import "react-loading-skeleton/dist/skeleton.css";
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/Footer/Footer";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

//export const metadata: Metadata = {
//  title: "PDFWhisper",
//  description: "Generated by create next app",
//  icons: {
//    icon: '/favicon.ico', // /public path
//  },
//};

//export const metadata = {
//  icons: {
//    icon: '/favicon.ico', // /public path
//  },
//}

//import Favicon from '/public/f.ico';

//export const metadata: Metadata = {
//  title: 'Next.js',
//  description: 'Generated by create next app',
//  icons: [{ rel: 'icon', url: Favicon.src }],
//};




//export const metadata: Metadata = {
//  icons: {
//    icon: ['/favicon.ico?v=4'],
//    apple: ['/apple-touch-icon.png?v=4'],
//    shortcut: ['/apple-touch-icon.png'],
//  },
//  manifest: '/site.webmanifest',
//};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
      <link rel="shortcut icon" href="/images/favicon.ico" />
      </Head>
      <Provider>
        <body
          className={cn(
            ` min-h-screen bg-background  font-sans antialiased grainy ${inter.className}`
          )}
        >
          <Navbar />
          <Toaster />
          {children}
          <Footer />
        </body>
      </Provider>
    </html>
  );
}
